package se.blick.app.domain.model

/** The persisted route identity shown on routine surfaces. */
data class RoutineRouteLabels(
    val origin: String,
    val destination: String?,
)

/**
 * Resolves route labels from the saved routine rather than from a currently selected departure
 * or journey leg. Journey Planner names are preferred for exact-destination routines because
 * they are the persisted A/B choices; the ordinary site/direction fields remain safe fallbacks
 * for older or partially populated rows.
 */
fun CommuteRoutine.routeLabels(): RoutineRouteLabels = when (type) {
    RoutineType.EXACT_DESTINATION -> RoutineRouteLabels(
        origin = journeyOriginName?.takeIf { it.isNotBlank() } ?: siteName,
        destination = journeyDestinationName?.takeIf { it.isNotBlank() }
            ?: destinationLabel?.takeIf { it.isNotBlank() },
    )
    RoutineType.LINE_DIRECTION -> RoutineRouteLabels(
        origin = siteName,
        destination = destinationLabel?.takeIf { it.isNotBlank() },
    )
}

/** Single formatting rule for every automatically generated routine name. */
fun formatRoutineName(origin: String?, destination: String?): String {
    val safeOrigin = origin?.trim()?.takeIf { it.isNotEmpty() }
    val safeDestination = destination?.trim()?.takeIf { it.isNotEmpty() }
    return when {
        safeOrigin != null && safeDestination != null -> "$safeOrigin → $safeDestination"
        safeOrigin != null -> safeOrigin
        safeDestination != null -> safeDestination
        else -> ""
    }
}

/**
 * Recognizes both today's generated name and formats legitimately generated by earlier builds.
 * Line-direction names previously used the line designation as their first component. Exact
 * destinations historically used the selected site name before the resolved journey-origin name
 * was persisted, so both saved origin representations are accepted.
 */
fun CommuteRoutine.hasAutomaticallyGeneratedName(): Boolean {
    val labels = routeLabels()
    val accepted = buildSet {
        add(formatRoutineName(labels.origin, labels.destination))
        when (type) {
            RoutineType.EXACT_DESTINATION ->
                add(formatRoutineName(siteName, journeyDestinationName ?: destinationLabel))
            RoutineType.LINE_DIRECTION ->
                add(formatRoutineName(lineDesignation, destinationLabel))
        }
    }
    return name in accepted
}
